'use client';

import { useEffect, useRef, useState } from 'react';
import { motion, useInView } from 'motion/react';
import { SectionHeading } from '@/components/ui/SectionHeading';

const stats = [
  { value: 95, suffix: '%', label: 'COVERAGE', sublabel: 'Code paths tested' },
  { value: 1284, suffix: '', label: 'TEST CASES', sublabel: 'Generated by AI' },
  { value: 47, suffix: '', label: 'DEFECTS FOUND', sublabel: 'Before production' },
  { value: 12.8, suffix: 'x', label: 'FASTER', sublabel: 'Than manual testing' },
];

function AnimatedNumber({ value, suffix }: { value: number; suffix: string }) {
  const [display, setDisplay] = useState(0);
  const ref = useRef<HTMLSpanElement>(null);
  const inView = useInView(ref, { once: true, margin: '-50px' });

  useEffect(() => {
    if (!inView) return;
    const duration = 1500;
    const start = performance.now();
    let raf: number;

    function tick(now: number) {
      const progress = Math.min((now - start) / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      setDisplay(value * eased);
      if (progress < 1) raf = requestAnimationFrame(tick);
    }
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [inView, value]);

  const formatted = value % 1 !== 0 ? display.toFixed(1) : Math.floor(display).toLocaleString();

  return (
    <span ref={ref} className="tabular-nums">
      {formatted}
      <span className="text-yellow-500">{suffix}</span>
    </span>
  );
}

export function Stats() {
  return (
    <section className="relative py-24 sm:py-32 px-6 sm:px-10 lg:px-20 overflow-hidden">
      {/* Background scan line */}
      <div className="absolute inset-0 bg-grid-yellow opacity-30" />

      <SectionHeading
        label="BY THE NUMBERS"
        title="The AI Testing Engine Delivers"
        description="Real metrics from simulated test runs across multiple project types."
      />

      <div className="mt-16 max-w-6xl mx-auto grid grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-8">
        {stats.map((stat, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-50px' }}
            transition={{ duration: 0.5, delay: i * 0.1 }}
            className="relative group"
          >
            <div className="relative p-6 sm:p-8 rounded-2xl border border-border bg-gradient-to-b from-card/50 to-transparent overflow-hidden">
              {/* Hover scanner */}
              <div className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity">
                <motion.div
                  className="absolute left-0 right-0 h-px bg-yellow-500/40"
                  animate={{ top: ['0%', '100%'] }}
                  transition={{ duration: 2, repeat: Infinity }}
                />
              </div>

              {/* Number */}
              <div className="relative z-10">
                <div className="text-4xl sm:text-5xl lg:text-6xl font-bold text-foreground tracking-tight">
                  <AnimatedNumber value={stat.value} suffix={stat.suffix} />
                </div>
                <div className="mt-2 font-mono text-xs text-yellow-500 tracking-widest">
                  {stat.label}
                </div>
                <div className="mt-1 text-xs text-muted-foreground">
                  {stat.sublabel}
                </div>
              </div>

              {/* Corner accent */}
              <div className="absolute top-3 right-3 w-6 h-6 border-l border-t border-yellow-500/20" />
              <div className="absolute bottom-3 left-3 w-6 h-6 border-r border-b border-yellow-500/20" />
            </div>
          </motion.div>
        ))}
      </div>
    </section>
  );
}
